stage:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/mkdev8793416/ec_ticketing_microservices

auth-tests:
  image: node:18
  stage: test
  script:
    - cd auth
    - npm install
    - npm run test:ci
