stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/mkdev8793416/ec_ticketing_microservices

auth-tests:
  stage: test
  image: node:18-bullseye
  script:
    - cd auth
    - npm install
    - npm run test:ci

orders-tests:
  stage: test
  image: node:18-bullseye
  script:
    - cd orders
    - npm install
    - npm run test:ci

tickets-tests:
  stage: test
  image: node:18-bullseye
  script:
    - cd tickets
    - npm install
    - npm run test:ci

auth-build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd auth
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE/auth:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE/auth:$CI_COMMIT_SHORT_SHA

orders-build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd orders
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE/orders:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE/orders:$CI_COMMIT_SHORT_SHA

tickets-build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd tickets
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE/tickets:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE/tickets:$CI_COMMIT_SHORT_SHA

payments-build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd payments
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE/tickets:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE/tickets:$CI_COMMIT_SHORT_SHA