stage:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/mkdev8793416/ec_ticketing_microservices

auth-tests:
  stage: test
  image: node:18
  script:
    - cd auth
    - npm install
    - npm run test:ci
  rules:
    - changes:
      - auth/**