stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/mkdev8793416/ec_ticketing_microservices
  DOCKER_HOST: ""

# used to debug docker runner issues
# docker-debug:
#   stage: test
#   image: docker:24.0.5
#   script:
#     - echo "Checking Docker socket..."
#     - ls -la /var/run/docker.sock
#     - docker ps
#   tags:
#     - docker


auth-tests:
  stage: test
  image: node:18-bullseye
  script:
    - export PATH="/usr/local/opt/node@18/bin:$PATH"
    - node -v      
    - which npm
    - cd auth
    - npm install
    - npm run test:ci
  tags:
    - docker

# orders-tests:
#   stage: test
#   image: node:18-bullseye
#   script:
#     - export PATH="/usr/local/opt/node@18/bin:$PATH"
#     - node -v      
#     - which npm
#     - cd orders
#     - npm install
#     - npm run test:ci
#   tags:
#     - docker

# tickets-tests:
#   stage: test
#   image: node:18-bullseye
#   script:
#     - export PATH="/usr/local/opt/node@18/bin:$PATH"
#     - node -v      
#     - which npm
#     - cd tickets
#     - npm install
#     - npm run test:ci
#   tags:
#     - docker 

auth-build:
  stage: build
  image: docker:24.0.5
  script:
    - cd auth
    - docker build -t $DOCKER_IMAGE/auth:$CI_COMMIT_SHORT_SHA .
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push $DOCKER_IMAGE/auth:$CI_COMMIT_SHORT_SHA
  tags:
    - docker

# orders-build:
#   stage: build
#   image: docker:24.0.5
#   script:
#     - cd orders
#     - docker build -t $DOCKER_IMAGE/orders:$CI_COMMIT_SHORT_SHA .
#     - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
#     - docker push $DOCKER_IMAGE/orders:$CI_COMMIT_SHORT_SHA
#   tags:
#     - docker

# tickets-build:
#   stage: build
#   image: docker:24.0.5
#   script:
#     - cd tickets
#     - docker build -t $DOCKER_IMAGE/tickets:$CI_COMMIT_SHORT_SHA .
#     - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
#     - docker push $DOCKER_IMAGE/tickets:$CI_COMMIT_SHORT_SHA
#   tags:
#     - docker

# payments-build:
#   stage: build
#   image: docker:24.0.5
#   script:
#     - cd payments
#     - docker build -t $DOCKER_IMAGE/payments:$CI_COMMIT_SHORT_SHA .
#     - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
#     - docker push $DOCKER_IMAGE/payments:$CI_COMMIT_SHORT_SHA
#   tags:
#     - docker

auth-deploy:
  stage: deploy
  image: alpine/k8s:1.27.4
  script:
    # - echo "$KUBECONFIG" > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    - sed -i "s|auth:.*|auth:$CI_COMMIT_SHORT_SHA|" infra/k8s/auth-depl.yaml
    - kubectl apply -f infra/k8s/auth-depl.yaml
  tags:
    - docker