stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/mkdev8793416/ec_ticketing_microservices

auth-tests:
  stage: test
  image: node:18-bullseye
  script:
    - cd auth
    - npm install
    - npm run test:ci

orders-tests:
  stage: test
  image: node:18-bullseye
  script:
    - cd orders
    - npm install
    - npm run test:ci

<<<<<<< HEAD
payments-tests:
  stage: test
  image: node:18-bullseye
  script:
    - cd payments
    - npm install
    - npm run test:ci
=======
# payments-tests:
#   stage: test
#   image: node:18-bullseye
#   script:
#     - cd payments
#     - npm install
#     - npm run test:ci
>>>>>>> 1b9c763 (chore: normalize line endings to LF)

tickets-tests:
  stage: test
  image: node:18-bullseye
  script:
    - cd tickets
    - npm install
    - npm run test:ci