replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

service:
  type: NodePort
  port: 5601
  nodePort: 30601

elasticsearchHosts: "http://elasticsearch-master:9200"

kibanaConfig:
  kibana.yml: |
    elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]

automountToken: false

security:
  enabled: false